In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [5]:
df = pd.read_csv('train.csv')
df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        7613 non-null   int64 
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 297.5+ KB


In [7]:
df.text.isna().sum()

0

In [8]:
X = df['text']
y = df['target']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123, stratify=y)

In [10]:
count_vectorizer = CountVectorizer(stop_words='english')

count_train = count_vectorizer.fit_transform(X_train.values)
count_test = count_vectorizer.transform(X_test.values)

In [11]:
nb_classifier = MultinomialNB()

nb_classifier.fit(count_train, y_train)

pred = nb_classifier.predict(count_test)

In [12]:
metrics.accuracy_score(y_test, pred)

0.7876532399299475

In [15]:
pred[:10]

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [16]:
metrics.confusion_matrix(y_test, pred, labels=[0, 1])

array([[1100,  203],
       [ 282,  699]])

In [17]:
testdf = pd.read_csv('test.csv')
testdf.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [18]:
X_new = testdf['text']

count_new = count_vectorizer.transform(X_new.values)

In [19]:
prediction = nb_classifier.predict(count_new)

In [20]:
prediction[:10]

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0])

In [21]:
test_prediction = pd.Series(prediction, name='target')
id_col = testdf['id']

result = pd.concat([id_col, test_prediction], axis=1)

result.head()

id  target
0   0       1
1   2       0
2   3       1
3   9       1
4  11       1

In [22]:
result.to_csv('mutinomialNB.csv', index=False)